const express = require("express");
const router = express.Router();
const verifyJWT = require("../../middleware/auth.middleware");
const authorizeRoles = require("../../middleware/role.middleware");
const { createAddress, getAddresses, updateAddress, deleteAddress } = require("../../controller/compneyOwner/address.controller");
router.get("/", verifyJWT, getAddresses);
router.post("/", verifyJWT, authorizeRoles("admin"), createAddress);
router.put("/:id", verifyJWT, authorizeRoles("admin"), updateAddress);
router.delete("/:id", verifyJWT, authorizeRoles("admin"), deleteAddress);
module.exports = router;