const express = require("express");
const router = express.Router();
const verifyJWT = require("../../middleware/auth.middleware");
const authorizeRoles = require("../../middleware/role.middleware");
const { createPlan, getAllPlans, updatePlan, getPlanById, updatePlanStatus, } = require("../../controller/supperAdmin/subscription.controller");
router.get("/", getAllPlans);
router.use(verifyJWT, authorizeRoles("super_admin"));
router.post("/", createPlan);
router.get("/:id", getPlanById);
router.put("/:id", updatePlan);
router.delete("/:id", updatePlanStatus);
module.exports = router;